spring.application.name=completablefuture-demo
#dashboard
spring.datasource.url=jdbc:mysql://localhost:3306/dashboarddb
spring.datasource.username=dashboard_user
spring.datasource.password=dashboard_pwd


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

debug=true